# Generated by Django 4.1.13 on 2024-07-15 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=6)),
                ('date_of_birth', models.DateField()),
                ('hire_date', models.DateField(blank=True, null=True)),
                ('rehire_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Terminated', 'Terminated'), ('Rehired', 'Rehired')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=255)),
                ('monthly_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('posted_date', models.DateField()),
                ('closed_date', models.DateField(blank=True, null=True)),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hiring.industry')),
            ],
        ),
        migrations.CreateModel(
            name='HiringStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_hiring_count', models.IntegerField()),
                ('revenue_generated', models.DecimalField(decimal_places=2, max_digits=15)),
                ('average_recruitment_time', models.IntegerField()),
                ('recorded_month', models.IntegerField()),
                ('recorded_year', models.IntegerField()),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hiring.industry')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_date', models.DateField()),
                ('status', models.CharField(choices=[('Applied', 'Applied'), ('Hired', 'Hired'), ('Rejected', 'Rejected')], max_length=8)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hiring.employee')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hiring.job')),
            ],
        ),
    ]
