# Generated by Django 4.1.13 on 2024-07-15 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiring', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='industry',
            old_name='industry_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='job_title',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('Applied', 'Applied'), ('Hired', 'Hired'), ('Rejected', 'Rejected')], max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10),
        ),
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Terminated', 'Terminated'), ('Rehired', 'Rehired')], max_length=20),
        ),
        migrations.DeleteModel(
            name='HiringStatistics',
        ),
    ]
